### ISSUE TITLE
More documentation for gryo/accel arguments

### ISSUE THREAD

**Issue by xetrics** [OneMadGypsy/upy-motion#2]
Can we get more documentation on the README explaining the difference/values of each accel/gyro constructor argument?

**Comment by OneMadGypsy** [comment]
All of the constants (except filter constants) are directly from the MPU6050 datasheet. For immediate clarity you can check the datasheet for the values that are giving you confusion. I will update my docs as you suggested, but it will be days before I have time. When I do, I'm just going to copy/paste  the datasheet description of these constants.
